# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-19 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0009_remove_answer_is_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionvote',
            name='vote_type',
            field=models.IntegerField(),
        ),
    ]
