# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-19 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0010_auto_20180219_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answervote',
            name='vote_type',
            field=models.IntegerField(),
        ),
    ]
