# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-27 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0012_auto_20180219_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votes',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='votes',
            name='object_id',
        ),
        migrations.AddField(
            model_name='votes',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qa.Answer'),
        ),
        migrations.AddField(
            model_name='votes',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qa.Question'),
        ),
    ]
